In [7]:
import pandas as pd

In [8]:
feeds_5k = pd.read_json("data/feeds_5k.jsonl", lines=True)
print(len(feeds_5k))
feeds_5k.head()

5000

,feed_id,title,feed_text,tags,language,created_at,source,url,views,embedding_input
0,EN_SIM_00000,Mental Health & Wellbeing for law students,"Actionable steps, resources, and templates to ...","[health, law, mindfulness, ml, stress]",en,2025-04-09 03:18:40+00:00,Career Center,https://example.com/en/en_sim_00000,25757,title: Mental Health & Wellbeing for law stude...
1,EN_SIM_00001,Tech & Coding for data science students,"Curated links + examples. Includes timelines, ...","[ai, python, sql, data, research]",en,2025-03-19 05:18:40+00:00,Career Center,https://example.com/en/en_sim_00001,24467,title: Tech & Coding for data science students...
2,EN_SIM_00002,Weekly plan: study + portfolio + wellbeing (fo...,"Curated links + examples. Includes timelines, ...","[clinical, statistics, presentation, leadershi...",en,2025-08-28 07:18:40+00:00,Career Center,https://example.com/en/en_sim_00002,9497,title: Weekly plan: study + portfolio + wellbe...
3,TH_SIM_00003,โร้ดแมป: จาก mechanical engineering ไปสาย phar...,สรุปขั้นตอน + แหล่งเรียนรู้ สำหรับนักศึกษา mec...,"[interview, mechanical, resume, pharmacovigila...",th,2025-04-28 03:18:40+00:00,Internship Radar TH,https://example.com/th/th_sim_00003,27861,title: โร้ดแมป: จาก mechanical engineering ไปส...
4,TH_SIM_00004,เช็กลิสต์สมัครฝึกงานสาย ux researcher,สรุปขั้นตอน + แหล่งเรียนรู้ สำหรับนักศึกษา acc...,"[health, ux, stress, wellbeing, accounting]",th,2025-07-06 06:18:40+00:00,Career Center TH,https://example.com/th/th_sim_00004,3558,title: เช็กลิสต์สมัครฝึกงานสาย ux researcher\n...

In [9]:
feeds_20k = pd.read_json("data/feeds_20k.jsonl", lines=True)
print(len(feeds_20k))
feeds_20k.head()

20000

,source,created_at,tags,feed_text,views,title,embedding_input,language,url,feed_id
0,Campus Digest,2026-02-15 02:18:40+00:00,"[events, clubs, campus, consultant, accounting]","Actionable steps, resources, and templates to ...",120299,Campus Life for accounting students,title: Campus Life for accounting students\nfe...,en,https://example.com/en/en_sim_14777,EN_SIM_14777
1,Campus Digest,2026-02-04 05:18:40+00:00,"[events, clubs, campus, pharmacovigilance, acc...","Actionable steps, resources, and templates to ...",49010,Campus Life for accounting students,title: Campus Life for accounting students\nfe...,en,https://example.com/en/en_sim_19813,EN_SIM_19813
2,Campus Digest,2026-02-22 09:18:40+00:00,"[events, clubs, campus, financial, accounting]","Curated links + examples. Includes timelines, ...",33206,Campus Life for accounting students,title: Campus Life for accounting students\nfe...,en,https://example.com/en/en_sim_28200,EN_SIM_28200
3,Campus Digest,2025-10-05 02:18:40+00:00,"[events, data, clubs, community, architecture]","Actionable steps, resources, and templates to ...",44623,Campus Life for architecture students,title: Campus Life for architecture students\n...,en,https://example.com/en/en_sim_04363,EN_SIM_04363
4,Campus Digest,2025-09-27 02:18:40+00:00,"[events, clubs, community, research, architect...","Actionable steps, resources, and templates to ...",7079,Campus Life for architecture students,title: Campus Life for architecture students\n...,en,https://example.com/en/en_sim_21111,EN_SIM_21111

In [10]:

# Find common feed_ids
common_feed_ids = set(feeds_5k["feed_id"]).intersection(feeds_20k["feed_id"])

print(f"Common feed_ids count: {len(common_feed_ids)}")

# Optional: view as sorted list
common_feed_ids_list = sorted(common_feed_ids)
print(common_feed_ids_list[:20])  # first 20

Common feed_ids count: 1955
['EN_SIM_00000', 'EN_SIM_00001', 'EN_SIM_00002', 'EN_SIM_00011', 'EN_SIM_00012', 'EN_SIM_00015', 'EN_SIM_00017', 'EN_SIM_00027', 'EN_SIM_00034', 'EN_SIM_00035', 'EN_SIM_00040', 'EN_SIM_00044', 'EN_SIM_00051', 'EN_SIM_00054', 'EN_SIM_00063', 'EN_SIM_00064', 'EN_SIM_00069', 'EN_SIM_00073', 'EN_SIM_00074', 'EN_SIM_00076']

In [12]:
common_feeds = feeds_5k[feeds_5k["feed_id"].isin(common_feed_ids)]
print(len(common_feeds))
common_feeds.head()

1955

,feed_id,title,feed_text,tags,language,created_at,source,url,views,embedding_input
0,EN_SIM_00000,Mental Health & Wellbeing for law students,"Actionable steps, resources, and templates to ...","[health, law, mindfulness, ml, stress]",en,2025-04-09 03:18:40+00:00,Career Center,https://example.com/en/en_sim_00000,25757,title: Mental Health & Wellbeing for law stude...
1,EN_SIM_00001,Tech & Coding for data science students,"Curated links + examples. Includes timelines, ...","[ai, python, sql, data, research]",en,2025-03-19 05:18:40+00:00,Career Center,https://example.com/en/en_sim_00001,24467,title: Tech & Coding for data science students...
2,EN_SIM_00002,Weekly plan: study + portfolio + wellbeing (fo...,"Curated links + examples. Includes timelines, ...","[clinical, statistics, presentation, leadershi...",en,2025-08-28 07:18:40+00:00,Career Center,https://example.com/en/en_sim_00002,9497,title: Weekly plan: study + portfolio + wellbe...
4,TH_SIM_00004,เช็กลิสต์สมัครฝึกงานสาย ux researcher,สรุปขั้นตอน + แหล่งเรียนรู้ สำหรับนักศึกษา acc...,"[health, ux, stress, wellbeing, accounting]",th,2025-07-06 06:18:40+00:00,Career Center TH,https://example.com/th/th_sim_00004,3558,title: เช็กลิสต์สมัครฝึกงานสาย ux researcher\n...
7,TH_SIM_00007,personal finance สำหรับนักศึกษา chemistry,สรุปขั้นตอน + แหล่งเรียนรู้ สำหรับนักศึกษา che...,"[student finance, budget, chemistry, scholarsh...",th,2025-05-05 11:18:40+00:00,Career Center TH,https://example.com/th/th_sim_00007,4663,title: personal finance สำหรับนักศึกษา chemist...

In [13]:
common_feeds.to_json("data/common_feeds.jsonl", orient="records", lines=True)

/var/folders/y3/lt1n9cfd58g_3nf7mrytx7_r0000gp/T/ipykernel_41118/2077090601.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  common_feeds.to_json("data/common_feeds.jsonl", orient="records", lines=True)